/*
 * This source file was generated by the Gradle 'init' task
 */
package org.isen.projet.carburant

import org.apache.logging.log4j.kotlin.Logging
import org.isen.projet.carburant.ctrl.CarburantController
import org.isen.projet.carburant.model.CarburantModel
import org.isen.projet.carburant.view.impl.CarburantTestView

class App{
    companion object : Logging
    fun doStuff(){
        logger.info("Projet")
        logger.debug("Carburant")
    }
}

fun main() {
    println("Start Test Logger Application...")
    //App().doStuff()
    val model = CarburantModel()
    val controller = CarburantController(model)
    val testGui = CarburantTestView(controller)

    controller.displayAll()
}
