/*
 * This source file was generated by the Gradle 'init' task
 */
package org.isen.projet.carburant

import org.apache.logging.log4j.kotlin.Logging

class App{
    companion object : Logging
    fun doStuff(){
        logger.info("Projet")
        logger.debug("Carburant")
    }
}

fun main() {
    println("Start Test Logger Application...")
    App().doStuff()
}
